### ISSUE TITLE
As a user, I can add a task by specifying a task description

### ISSUE THREAD

**Issue by C-YanHua** [cs2103jan2015-t13-3j/main#3]
so that I can record tasks that I need to complete.

ID: addTask

**Comment by AppleSky** [comment]
I will do this part.

**Comment by TimothyTam** [comment]
Thanks for starting to code,

Somethings I noted down for the future:

add get X from Bob from 1000 to 1100
	-> Fails, need to check the final "from". Same as "to". I think can make a method to check the final appearance of any word in the command, so can use for the other keywords like "from","to", "every", etc.

add task from 1100 to 1000
	-> Success, should fail unless date stated is different. (Can ignore this until adding date is implemented)

add task from 1000 to 4000
	-> App hangs due to exception, must catch during LocalTime.of(xxx)

Also, I think in the final product we need to add floating tasks (Tasks with no time set, when the date exceeds, it will automatically push the task to tomorrow). I'm not sure if that's the meaning of floating tasks.

**Comment by AppleSky** [comment]
You're right. I only did the very basic of adding a task. It will need a lot more improvements to handle more test cases / exceptions.

add get X from Bob from 1000 to 1100
Right now i'm only splitting with regex expression for (from or to) with trailing blank space(s). A method to check for final appearance is good.

For now i haven't do any exceptions handling for the time input, wasn't sure how we want to go about the time format. Eg. "hhmm" or "hh:mm".

Oh and i didn't do date yet because i can't seem to view the date in the GUI unless i change parts of "TaskOverviewController.java". Are you able to view the date when you start the program? I think it would be better for you to handle the GUI part so it won't get too confusing.

**Comment by TimothyTam** [comment]
errr, when i choose a date(e.g. today, tomorrow, tuesday, specific date) it will not show the dates. (I not sure how we want this also)
i only show date when it shows "All" or when show by tags. try "show all" or "show important"

**Comment by TimothyTam** [comment]
oya, i just realised got 
	private static final String DATE_FORMAT = "yyyy-MM-dd";
	private static final String TIME_FORMAT = "kkmm";
at the top of MainApp.java

can write a method to check date and time.

boolean checkDate(){
		SimpleDateFormat format = new SimpleDateFormat(DATE_FORMAT);
		try {
			format.parse(command[1]);
			return true;
		} catch (ParseException e) {
			return false;
		}
}

**Comment by AppleSky** [comment]
Okay noted, shall look into it again.

**Comment by TimothyTam** [comment]
oh, paiseh, i must "show [all|date] <tags>" must have either all or a valid date in before tags, so show important won't work. 
I might change that but I most likely will not since I can't identify what is a tag and what is not for now.
