### ISSUE TITLE
The getEndDateTime method inside parser has a minor bug

### ISSUE THREAD

**Issue by C-YanHua** [cs2103jan2015-t13-3j/main#43]
for example, to 13/4 asdasdada will return a end date of 13/4 asdasdsd. This is not handled well. The end date is then normally parsed into a new DateTime object and the new DateTime object will treat 13/4 asdasdsd as a valid input as the DateTime object will take 13/4 as a date, and asdasdsd as a time where the validation for the time part will fail. This is an issue as 13/4 asdasdsd is still considered as a valid DateTime object with only the date but in reality it should be not be treated as a valid DateTime object.

**Comment by LeeWeiHong** [comment]
To be honest i'm not sure how to fix this. getEndDateTime takes the string after to, say "to <string>" or the string between to and for/every, say "to <string> for/every". How can you write a regex to take 13/4 from "to 13/4 asd"? 

As for DateTime because SimpleDateFormat takes the first matching sequence, once a valid date is match, the remaining is ignored.

**Comment by C-YanHua** [comment]
Valid point. Actually this does not really affect our command input as the user actually did input valid fields infront. In our case, we check for rubbish text within the fields rather than rubbish text outside the fields. I think this does not really affect the program much, but we can ask chun kit for his opinion whether this is critical to the project.

**Comment by TimothyTam** [comment]
fixed? fixed. I think.
